version: "3.8"

services:
  php-fpm:
    build: .
    networks:
      - app_network
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    networks:
      - app_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html

networks:
  app_network:
    name: 'app_network'
